{% set name = "consolemd" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9bededcc256155ad52194c78a4fb9d9d8e93adc728e7bbdea0ab1eae7f590ebd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - consolemd = consolemd.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - click
    - commonmark
    - pygments
    - python >={{ python_min }}
    - setproctitle

test:
  imports:
    - consolemd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kneufeld/consolemd
  summary: ConsoleMD renders markdown to the console
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - chrisburr
